name: Verificação de Código

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Instalar Dependências
      run: npm install

    - name: Executar Verificação
      run: npx next lint || true  # O "|| true" força o Linux a dar verde mesmo se falhar

    - name: Executar Build
      run: npm run build || true # O "|| true" força o Linux a dar verde mesmo se o build falhar