name: Verificação de Código

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Instalar Dependências
      run: npm install

    - name: Executar Verificação (Lint)
      run: npx next lint --dir src
      continue-on-error: true

    - name: Executar Build do Next.js
      run: npm run build
      continue-on-error: true
